[package]
name = "black_scholes_calc"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.24" # Interface Gr√°fica
statrs = "0.16"
yahoo_finance_api = "2.3"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"